README.md, pnpm-lock.yaml, src/App.vue
- The issue of reopening the file in the presentation viewer is fixed in this PR.
- Updated the pnpm lock file
- Updated the documentation
Fixes https://github.com/JankariTech/web-app-presentation-viewer/issues/13
Fixes https://github.com/JankariTech/web-app-presentation-viewer/issues/11
[Screencast from 2024-02-18 15-40-51.webm](https://github.com/JankariTech/web-app-presentation-viewer/assets/8559121/6429f094-f4bd-44d3-826a-90cd4a0b1ea5)
=> [FIX] Fixed presentation reopening issues

src/App.vue
- The slide will adapt according to ownCloud web dark and light theme
Fixes https://github.com/JankariTech/web-app-presentation-viewer/issues/17
[Screencast from 2024-02-20 16-22-47.webm](https://github.com/JankariTech/web-app-presentation-viewer/assets/8559121/f4a7603d-d22b-491b-bff6-5099cd555bcc)
=> Fix: change color according to theme of web

Dockerfile, docker/vhost.conf
- Added a docker file to build image for presentation viewer
- Added server configuration
Merge this PR after https://github.com/JankariTech/web-app-presentation-viewer/pull/9
Related issue: 
- https://github.com/JankariTech/web-app-presentation-viewer/issues/12
=> Added a docker file for presentation viewer

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/config.yml
- Added issue template form to report issue or bugs
=> Added issue template for bug/issue report

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/feature.yaml
- Added the feature request template.
=> Added feature template for new feature request

.editorconfig, .eslintrc.cjs, .github/ISSUE_TEMPLATE/bug.yaml, .github/workflows/lint.yml, .prettierrc, package.json, pnpm-lock.yaml, src/App.vue, src/index.ts, tsconfig.json, vite.config.ts
Setup code lint and format with eslint
Also, added lint github action workflow
Fixes #33
=> setup code lint and format

package.json
Included more `.cjs` and `.mjs` file formats for linting
=> style: include more js file formats for lint

.gitignore, cucumber.cjs, package.json, pnpm-lock.yaml, tests/e2e/config.js, tests/e2e/features/presentationViewer.feature, tests/e2e/filesForUpload/test-markdown.md, tests/e2e/hooks.js, tests/e2e/pageObjects/OcisPage.js, tests/e2e/pageObjects/PresentationViewerPage.js, tests/e2e/stepDefinitions/presentationViewerContext.js, tests/e2e/utils/apiHelper.js, tests/e2e/utils/fileHelper.js, tests/e2e/utils/userHelper.js, tests/package.json
Added e2e tests setup along with configurations.
Implemented test scenarios for previewing slides in presentation viewer (including uploading of markdown file using API).
=> test: setup e2e test

.github/workflows/ci.yml, CHANGELOG.md, README.md, docker-compose.yml, package.json, pnpm-lock.yaml
=> chore: prepare release v1.0.0

.github/workflows/ci.yml, docker-compose.yml
- Fixes <issue_link>
- Part of <issue_link>
- test case 1:
- test case 2:
=> changing ocis to ocis rolling

package.json, pnpm-lock.yaml
Pull required web packages from the pinned commit (commit of released tag). This makes unit testing possible and easy.
=> build: pin web packages to release commit

src/App.vue
Pass element ref to the Reveal. this makes the code testable.
=> refactor: provide element ref to reveal

.github/workflows/ci.yml, .gitignore, package.json, pnpm-lock.yaml, tests/unit/App.spec.ts, tests/unit/__snapshots__/App.spec.ts.snap, tsconfig.json, vitest.config.ts
Added unit test setup and one snapshot test
- Resolves #15
- test environment: :raised_back_of_hand:
=> test(unit): setup unit test

README.md, dev/docker/csp.yml, docker-compose.override.example.yml, vite.config.ts
Fix local dev setup when running with WEB_ASSET_APPS_PATH enabled
=> fix: local dev setup for WEB_ASSET

.github/workflows/release.yml, CHANGELOG.md, package.json, public/manifest.json
- Part of #71
- test case 1:
- test case 2:
=> chore: prepare release 2.0.0

config/web.config.json.sample, dev/docker/web.config.json, public/manifest.json, tests/e2e/ci/web.config.json
=> refactor: rename app-id to mdpresentation-viewer

package.json
- Fixes <issue_link>
- Part of <issue_link>
- test case 1:
- test case 2:
=> chore: bump version to 2.1.0-alpha.1

CHANGELOG.md, src/App.vue
- Fixes #40
- test environment: :raised_back_of_hand:
=> fix: code blocks in lists are not using existing space

README.md
the link changed on the server
=> update demonstration link

package-common.json
I forgot to update the version there
- Fixes <issue_link>
- Part of <issue_link>
- test case 1:
- test case 2:
=> fix version in package.json

package-common.json, src/App.vue, src/css/variables.css
Use [RevealAwesoMD](https://github.com/opf/revealjs-awesoMD) as the markdown compiler, that supports e.g. alert boxes (depends on https://github.com/opf/revealjs-awesoMD/pull/20).
- Part of #21
being more awesome!
:robot:
=> use RevealAwesoMD for more awsomeness

tests/unit/__snapshots__/App.spec.ts.snap
Don't know how the tests passed in PRs, but after merge they are failing.
This fixes the unit test by updating the snapshot
=> fix unit tests
